# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('type_of_user', models.CharField(max_length=30, null=True)),
                ('national_id', models.IntegerField(null=True)),
                ('phonenumber', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60, null=True)),
                ('nearest_town', models.CharField(max_length=50)),
            ],
        ),
    ]
