# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midwife', '0002_session_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
